# Generated by Django 5.1.6 on 2025-03-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SuddenExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expense', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='MandatoryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expense', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mandatory', models.FloatField()),
                ('basic_needs', models.FloatField()),
                ('sudden_expenses', models.FloatField()),
                ('savings', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('actual_salary', models.FloatField()),
                ('active_salary', models.FloatField()),
                ('mandatory_limit', models.FloatField()),
                ('basic_needs_limit', models.FloatField()),
                ('sudden_expenses_limit', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='BasicNeedsExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expense', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
    ]
